# Linear non-Gaussian models (DirectLiNGAM / ICA-LiNGAM)

[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Abel-ai-lab/andrey/blob/main/examples/lingam.ipynb)

When the mechanisms are linear and the noise is non-Gaussian, the data identify a single DAG, not
only its equivalence class. DirectLiNGAM finds a causal order one variable at a time with a
pairwise independence measure. ICA-LiNGAM runs independent component analysis (FastICA) and reads
the order from the unmixing matrix. Both return a fully oriented DAG, a causal order, and edge
weights.

## Start

Choose a CPU runtime and run this cell first. In Colab it installs `andrey-core==0.6.0` from PyPI;
local kernels use the installed environment.

In [1]:
import os
import sys

IN_COLAB = "google.colab" in sys.modules

if IN_COLAB:
    os.environ["ANDREY_DEVICE"] = "cpu"
    !pip install --quiet "andrey-core[numba,viz]==0.6.0" pandas

In [2]:
import numpy as np
import pandas as pd
from IPython.display import display

import andrey
import andrey.metrics as metrics
import andrey.viz
from andrey.data import benchmarks

## Data

`lingam_sf` draws a scale-free graph with linear mechanisms and uniform noise: here 8 variables
and 2,000 samples.

In [3]:
seed = 7
dataset = benchmarks.scm("lingam_sf", d=8).sample(n=2000, seed=seed, scale="standardize")
X, truth = dataset.data, dataset.observed_graph
print(f"{X.shape[0]} observations, {X.shape[1]} variables, seed {seed}")
display(andrey.viz.draw(truth))

2000 observations, 8 variables, seed 7

'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 564 259" width="100%" font-family="Inter, system-ui, sans-serif"><rect width="564" height="259" fill="#fafbfc"/><line x1="309.11" y1="124.87" x2="44.94" y2="99.30" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="319.06,125.83 309.59,119.89 308.63,129.84" fill="#3a4658" stroke-linejoin="round"/><line x1="344.80" y1="129.35" x2="509.35" y2="158.55" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.20,160.29 510.23,153.62 508.48,163.47" fill="#3a4658" stroke-linejoin="round"/><line x1="310.11" y1="120.02" x2="244.37" y2="98.81" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="319.63,123.09 311.65,115.26 308.58,124.78" fill="#3a4658" stroke-linejoin="round"/><line x1="344.43" y1="123.27" x2="410.01" y2="103.17" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="419.57,100.24 408.54,98.39 411.47,107.96" fill="#3a4658" stroke-linejoin="round"/><line x1="45.00" y1="97.84" x2="209.00" y2="95.19" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="219.00,95.03 208.92,90.19 209.08,100.19" fill="#3a4658" stroke-linejoin="round"/><line x1="42.84" y1="90.88" x2="112.82" y2="44.61" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="121.16,39.09 110.06,40.44 115.57,48.78" fill="#3a4658" stroke-linejoin="round"/><line x1="512.82" y1="149.88" x2="442.84" y2="103.61" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="521.16,155.39 515.57,145.71 510.06,154.05" fill="#3a4658" stroke-linejoin="round"/><line x1="509.29" y1="166.23" x2="144.83" y2="225.01" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.17,164.63 508.50,161.29 510.09,171.16" fill="#3a4658" stroke-linejoin="round"/><line x1="212.53" y1="82.58" x2="143.00" y2="38.84" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="221.00,87.90 215.19,78.34 209.87,86.81" fill="#3a4658" stroke-linejoin="round"/><line x1="218.13" y1="113.17" x2="139.84" y2="216.71" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="224.16,105.19 214.14,110.15 222.12,116.18" fill="#3a4658" stroke-linejoin="round"/><line x1="444.25" y1="92.09" x2="510.32" y2="68.64" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.75,65.30 508.65,63.93 512.00,73.36" fill="#3a4658" stroke-linejoin="round"/><line x1="144.97" y1="32.86" x2="509.06" y2="59.29" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.03,60.01 509.42,54.30 508.70,64.27" fill="#3a4658" stroke-linejoin="round"/><circle cx="332.00" cy="127.08" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="332.00" y="127.08" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">0</text><circle cx="32.00" cy="98.05" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="32.00" y="98.05" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">1</text><circle cx="532.00" cy="162.56" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="532.00" y="162.56" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">2</text><circle cx="232.00" cy="94.82" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="232.00" y="94.82" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">3</text><circle cx="432.00" cy="96.44" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="432.00" y="96.44" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">4</text><circle cx="132.00" cy="31.92" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="132.00" y="31.92" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">5</text><circle cx="532.00" cy="60.95" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="532.00" y="60.95" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">6</text><circle cx="132.00" cy="227.08" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="132.00" y="227.08" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">7</text></svg>'

## Fit both methods

DirectLiNGAM is deterministic. ICA-LiNGAM starts FastICA from a random point; `random_state` fixes
it, so a run repeats exactly.

In [4]:
results = {
    "DirectLiNGAM": andrey.direct_lingam(X),
    "ICA-LiNGAM": andrey.ica_lingam(X, random_state=0),
}
for name, result in results.items():
    print(f"{name}: {result.structure.kind}, causal order {result.ordering}")
    display(andrey.viz.draw(result.structure))

DirectLiNGAM: dag, causal order (7, 1, 5, 3, 0, 4, 6, 2)

'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 564 259" width="100%" font-family="Inter, system-ui, sans-serif"><rect width="564" height="259" fill="#fafbfc"/><line x1="309.11" y1="124.87" x2="44.94" y2="99.30" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="319.06,125.83 309.59,119.89 308.63,129.84" fill="#3a4658" stroke-linejoin="round"/><line x1="344.80" y1="129.35" x2="509.35" y2="158.55" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.20,160.29 510.23,153.62 508.48,163.47" fill="#3a4658" stroke-linejoin="round"/><line x1="310.11" y1="120.02" x2="244.37" y2="98.81" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="319.63,123.09 311.65,115.26 308.58,124.78" fill="#3a4658" stroke-linejoin="round"/><line x1="344.43" y1="123.27" x2="410.01" y2="103.17" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="419.57,100.24 408.54,98.39 411.47,107.96" fill="#3a4658" stroke-linejoin="round"/><line x1="45.00" y1="97.84" x2="209.00" y2="95.19" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="219.00,95.03 208.92,90.19 209.08,100.19" fill="#3a4658" stroke-linejoin="round"/><line x1="42.84" y1="90.88" x2="112.82" y2="44.61" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="121.16,39.09 110.06,40.44 115.57,48.78" fill="#3a4658" stroke-linejoin="round"/><line x1="512.82" y1="149.88" x2="442.84" y2="103.61" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="521.16,155.39 515.57,145.71 510.06,154.05" fill="#3a4658" stroke-linejoin="round"/><line x1="509.29" y1="166.23" x2="144.83" y2="225.01" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.17,164.63 508.50,161.29 510.09,171.16" fill="#3a4658" stroke-linejoin="round"/><line x1="212.53" y1="82.58" x2="143.00" y2="38.84" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="221.00,87.90 215.19,78.34 209.87,86.81" fill="#3a4658" stroke-linejoin="round"/><line x1="218.13" y1="113.17" x2="139.84" y2="216.71" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="224.16,105.19 214.14,110.15 222.12,116.18" fill="#3a4658" stroke-linejoin="round"/><line x1="444.25" y1="92.09" x2="510.32" y2="68.64" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.75,65.30 508.65,63.93 512.00,73.36" fill="#3a4658" stroke-linejoin="round"/><line x1="144.97" y1="32.86" x2="509.06" y2="59.29" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.03,60.01 509.42,54.30 508.70,64.27" fill="#3a4658" stroke-linejoin="round"/><circle cx="332.00" cy="127.08" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="332.00" y="127.08" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">0</text><circle cx="32.00" cy="98.05" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="32.00" y="98.05" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">1</text><circle cx="532.00" cy="162.56" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="532.00" y="162.56" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">2</text><circle cx="232.00" cy="94.82" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="232.00" y="94.82" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">3</text><circle cx="432.00" cy="96.44" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="432.00" y="96.44" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">4</text><circle cx="132.00" cy="31.92" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="132.00" y="31.92" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">5</text><circle cx="532.00" cy="60.95" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="532.00" y="60.95" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">6</text><circle cx="132.00" cy="227.08" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="132.00" y="227.08" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">7</text></svg>'

ICA-LiNGAM: dag, causal order (1, 5, 7, 3, 0, 4, 2, 6)

'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 564 259" width="100%" font-family="Inter, system-ui, sans-serif"><rect width="564" height="259" fill="#fafbfc"/><line x1="309.11" y1="124.87" x2="44.94" y2="99.30" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="319.06,125.83 309.59,119.89 308.63,129.84" fill="#3a4658" stroke-linejoin="round"/><line x1="344.80" y1="129.35" x2="509.35" y2="158.55" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.20,160.29 510.23,153.62 508.48,163.47" fill="#3a4658" stroke-linejoin="round"/><line x1="310.11" y1="120.02" x2="244.37" y2="98.81" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="319.63,123.09 311.65,115.26 308.58,124.78" fill="#3a4658" stroke-linejoin="round"/><line x1="344.43" y1="123.27" x2="410.01" y2="103.17" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="419.57,100.24 408.54,98.39 411.47,107.96" fill="#3a4658" stroke-linejoin="round"/><line x1="45.00" y1="97.84" x2="209.00" y2="95.19" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="219.00,95.03 208.92,90.19 209.08,100.19" fill="#3a4658" stroke-linejoin="round"/><line x1="42.84" y1="90.88" x2="112.82" y2="44.61" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="121.16,39.09 110.06,40.44 115.57,48.78" fill="#3a4658" stroke-linejoin="round"/><line x1="512.82" y1="149.88" x2="442.84" y2="103.61" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="521.16,155.39 515.57,145.71 510.06,154.05" fill="#3a4658" stroke-linejoin="round"/><line x1="509.29" y1="166.23" x2="144.83" y2="225.01" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.17,164.63 508.50,161.29 510.09,171.16" fill="#3a4658" stroke-linejoin="round"/><line x1="212.53" y1="82.58" x2="143.00" y2="38.84" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="221.00,87.90 215.19,78.34 209.87,86.81" fill="#3a4658" stroke-linejoin="round"/><line x1="218.13" y1="113.17" x2="139.84" y2="216.71" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="224.16,105.19 214.14,110.15 222.12,116.18" fill="#3a4658" stroke-linejoin="round"/><line x1="444.25" y1="92.09" x2="510.32" y2="68.64" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.75,65.30 508.65,63.93 512.00,73.36" fill="#3a4658" stroke-linejoin="round"/><line x1="144.97" y1="32.86" x2="509.06" y2="59.29" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.03,60.01 509.42,54.30 508.70,64.27" fill="#3a4658" stroke-linejoin="round"/><circle cx="332.00" cy="127.08" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="332.00" y="127.08" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">0</text><circle cx="32.00" cy="98.05" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="32.00" y="98.05" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">1</text><circle cx="532.00" cy="162.56" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="532.00" y="162.56" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">2</text><circle cx="232.00" cy="94.82" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="232.00" y="94.82" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">3</text><circle cx="432.00" cy="96.44" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="432.00" y="96.44" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">4</text><circle cx="132.00" cy="31.92" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="132.00" y="31.92" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">5</text><circle cx="532.00" cy="60.95" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="532.00" y="60.95" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">6</text><circle cx="132.00" cy="227.08" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="132.00" y="227.08" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">7</text></svg>'

## Edge weights

`weighted_adjacency[i, j]` is the coefficient of variable `i` in the equation for variable `j`, so
each nonzero entry is an edge `i -> j`.

In [5]:
pd.DataFrame(results["ICA-LiNGAM"].weighted_adjacency).round(2)

      0    1     2     3     4     5     6    7
0  0.00  0.0  0.47  0.00  0.79  0.00  0.00  0.0
1  0.66  0.0  0.00  0.38  0.00 -0.72  0.00  0.0
2  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.0
3  0.76  0.0  0.00  0.00  0.00  0.00  0.00  0.0
4  0.00  0.0 -0.72  0.00  0.00  0.00  0.51  0.0
5  0.00  0.0  0.00  0.94  0.00  0.00 -0.71  0.0
6  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.0
7  0.00  0.0 -0.77  0.38  0.00  0.00  0.00  0.0

## Check accuracy over ten datasets

SHD counts errors against the true DAG; lower is better. The empty graph's SHD is the number of
true edges. The table covers ten seeds and their median.

In [6]:
methods = {
    "DirectLiNGAM": lambda X: andrey.direct_lingam(X),
    "ICA-LiNGAM": lambda X: andrey.ica_lingam(X, random_state=0),
}
rows = {}
for s in range(10):
    draw = benchmarks.scm("lingam_sf", d=8).sample(n=2000, seed=s, scale="standardize")
    d = draw.observed_graph.n_nodes
    empty = andrey.GraphStructure.from_numpy(np.zeros((d, d), dtype=np.uint8), kind="dag")
    rows[s] = {"Empty graph": metrics.score(empty, draw.observed_graph)["shd"]}
    for name, fit in methods.items():
        rows[s][name] = metrics.score(fit(draw.data), draw.observed_graph)["shd"]
shd = pd.DataFrame(rows)
shd.columns.name = "seed"
shd["median"] = shd.median(axis=1)
shd

seed           0   1   2   3   4   5   6   7   8   9  median
Empty graph   12  12  12  12  12  12  12  12  12  12    12.0
DirectLiNGAM   0   0   0   0   0   0   0   0   0   0     0.0
ICA-LiNGAM     0   8   0   0   6   0   0   0   0   1     0.0

## When to use them

Both methods rely on non-Gaussian noise. With Gaussian noise the order is not identified; PC, GES,
BOSS, or GRaSP return the CPDAG that the data do support. ICA-LiNGAM needs many samples: at
`n = 10d`, the size the [release cards](https://andrey.abel.ai/docs/benchmarks.html) use, it scores
worse than the empty graph, and this notebook uses `n = 250d`. Change `seed`, `d`, or `n` and rerun
to see how each method responds.