# Linear non-Gaussian models (DirectLiNGAM / ICA-LiNGAM / MultiGroupDirectLiNGAM / GIN)

[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Abel-ai-lab/andrey/blob/main/examples/lingam.ipynb)

When the mechanisms are linear and the noise is non-Gaussian, the data identify a single DAG, not
only its equivalence class. DirectLiNGAM finds a causal order one variable at a time with a
pairwise independence measure. ICA-LiNGAM runs independent component analysis (FastICA) and reads
the order from the unmixing matrix. Both return a fully oriented DAG, a causal order, and edge
weights. MultiGroupDirectLiNGAM fits several datasets that share one causal order, and GIN finds
the latent variables that observed indicators measure.

## Start

Choose a CPU runtime and run this cell first. In Colab it installs `andrey-core==0.6.0` from PyPI;
local kernels use the installed environment.

In [1]:
import os
import sys

IN_COLAB = "google.colab" in sys.modules

if IN_COLAB:
    os.environ["ANDREY_DEVICE"] = "cpu"
    !pip install --quiet "andrey-core[viz]==0.6.0" pandas

In [2]:
import numpy as np
import pandas as pd
from IPython.display import display

import andrey
import andrey.metrics as metrics
import andrey.viz
from andrey.data import benchmarks

## Data

`lingam_sf` draws a scale-free graph with linear mechanisms and uniform noise: here 8 variables
and 2,000 samples.

In [3]:
seed = 7
dataset = benchmarks.scm("lingam_sf", d=8).sample(n=2000, seed=seed, scale="standardize")
X, truth = dataset.data, dataset.observed_graph
print(f"{X.shape[0]} observations, {X.shape[1]} variables, seed {seed}")
display(andrey.viz.draw(truth))

2000 observations, 8 variables, seed 7

'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 564 262" width="100%" font-family="Inter, system-ui, sans-serif"><rect width="564" height="262" fill="#fafbfc"/><line x1="442.84" y1="153.67" x2="512.82" y2="107.40" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="521.16,101.88 510.06,103.23 515.57,111.57" fill="#3a4658" stroke-linejoin="round"/><line x1="444.19" y1="165.36" x2="510.44" y2="189.94" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.81,193.41 512.18,185.25 508.70,194.62" fill="#3a4658" stroke-linejoin="round"/><line x1="409.00" y1="160.84" x2="345.00" y2="160.84" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="419.00,160.84 409.00,155.84 409.00,165.84" fill="#3a4658" stroke-linejoin="round"/><line x1="139.84" y1="219.82" x2="218.13" y2="116.28" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="224.16,108.31 214.14,113.27 222.12,119.30" fill="#3a4658" stroke-linejoin="round"/><line x1="144.96" y1="229.15" x2="509.07" y2="199.78" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.04,198.98 508.67,194.80 509.48,204.77" fill="#3a4658" stroke-linejoin="round"/><line x1="112.82" y1="217.51" x2="42.84" y2="171.24" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="121.16,223.02 115.57,213.34 110.06,221.68" fill="#3a4658" stroke-linejoin="round"/><line x1="510.16" y1="101.93" x2="344.34" y2="156.76" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.66,98.79 508.59,97.18 511.73,106.68" fill="#3a4658" stroke-linejoin="round"/><line x1="509.28" y1="91.14" x2="144.84" y2="33.83" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.16,92.69 510.06,86.20 508.50,96.08" fill="#3a4658" stroke-linejoin="round"/><line x1="210.16" y1="105.16" x2="44.34" y2="159.98" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="219.66,102.02 208.59,100.41 211.73,109.90" fill="#3a4658" stroke-linejoin="round"/><line x1="243.00" y1="104.86" x2="312.53" y2="148.59" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="321.00,153.92 315.19,144.36 309.87,152.82" fill="#3a4658" stroke-linejoin="round"/><line x1="212.82" y1="85.25" x2="142.84" y2="38.98" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="221.16,90.76 215.57,81.08 210.06,89.42" fill="#3a4658" stroke-linejoin="round"/><line x1="45.00" y1="163.92" x2="309.00" y2="161.09" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="319.00,160.98 308.95,156.09 309.06,166.09" fill="#3a4658" stroke-linejoin="round"/><circle cx="432.00" cy="160.84" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="432.00" y="160.84" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">0</text><circle cx="132.00" cy="230.19" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="132.00" y="230.19" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">1</text><circle cx="532.00" cy="94.71" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="532.00" y="94.71" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">2</text><circle cx="232.00" cy="97.94" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="232.00" y="97.94" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">3</text><circle cx="532.00" cy="197.94" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="532.00" y="197.94" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">4</text><circle cx="32.00" cy="164.06" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="32.00" y="164.06" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">5</text><circle cx="332.00" cy="160.84" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="332.00" y="160.84" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">6</text><circle cx="132.00" cy="31.81" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="132.00" y="31.81" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">7</text></svg>'

## Fit both methods

DirectLiNGAM is deterministic. ICA-LiNGAM starts FastICA from a random point; `random_state` fixes
it, so a run repeats exactly.

In [4]:
results = {
    "DirectLiNGAM": andrey.direct_lingam(X),
    "ICA-LiNGAM": andrey.ica_lingam(X, random_state=0),
}
for name, result in results.items():
    print(f"{name}: {result.structure.kind}, causal order {result.ordering}")
    display(andrey.viz.draw(result.structure))

DirectLiNGAM: dag, causal order (7, 5, 1, 3, 6, 0, 4, 2)

'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 564 262" width="100%" font-family="Inter, system-ui, sans-serif"><rect width="564" height="262" fill="#fafbfc"/><line x1="442.84" y1="153.67" x2="512.82" y2="107.40" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="521.16,101.88 510.06,103.23 515.57,111.57" fill="#3a4658" stroke-linejoin="round"/><line x1="444.19" y1="165.36" x2="510.44" y2="189.94" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.81,193.41 512.18,185.25 508.70,194.62" fill="#3a4658" stroke-linejoin="round"/><line x1="409.00" y1="160.84" x2="345.00" y2="160.84" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="419.00,160.84 409.00,155.84 409.00,165.84" fill="#3a4658" stroke-linejoin="round"/><line x1="139.84" y1="219.82" x2="218.13" y2="116.28" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="224.16,108.31 214.14,113.27 222.12,119.30" fill="#3a4658" stroke-linejoin="round"/><line x1="144.96" y1="229.15" x2="509.07" y2="199.78" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.04,198.98 508.67,194.80 509.48,204.77" fill="#3a4658" stroke-linejoin="round"/><line x1="112.82" y1="217.51" x2="42.84" y2="171.24" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="121.16,223.02 115.57,213.34 110.06,221.68" fill="#3a4658" stroke-linejoin="round"/><line x1="510.16" y1="101.93" x2="344.34" y2="156.76" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.66,98.79 508.59,97.18 511.73,106.68" fill="#3a4658" stroke-linejoin="round"/><line x1="509.28" y1="91.14" x2="144.84" y2="33.83" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.16,92.69 510.06,86.20 508.50,96.08" fill="#3a4658" stroke-linejoin="round"/><line x1="210.16" y1="105.16" x2="44.34" y2="159.98" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="219.66,102.02 208.59,100.41 211.73,109.90" fill="#3a4658" stroke-linejoin="round"/><line x1="243.00" y1="104.86" x2="312.53" y2="148.59" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="321.00,153.92 315.19,144.36 309.87,152.82" fill="#3a4658" stroke-linejoin="round"/><line x1="212.82" y1="85.25" x2="142.84" y2="38.98" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="221.16,90.76 215.57,81.08 210.06,89.42" fill="#3a4658" stroke-linejoin="round"/><line x1="45.00" y1="163.92" x2="309.00" y2="161.09" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="319.00,160.98 308.95,156.09 309.06,166.09" fill="#3a4658" stroke-linejoin="round"/><circle cx="432.00" cy="160.84" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="432.00" y="160.84" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">0</text><circle cx="132.00" cy="230.19" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="132.00" y="230.19" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">1</text><circle cx="532.00" cy="94.71" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="532.00" y="94.71" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">2</text><circle cx="232.00" cy="97.94" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="232.00" y="97.94" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">3</text><circle cx="532.00" cy="197.94" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="532.00" y="197.94" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">4</text><circle cx="32.00" cy="164.06" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="32.00" y="164.06" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">5</text><circle cx="332.00" cy="160.84" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="332.00" y="160.84" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">6</text><circle cx="132.00" cy="31.81" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="132.00" y="31.81" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">7</text></svg>'

ICA-LiNGAM: dag, causal order (5, 1, 7, 3, 6, 0, 2, 4)

'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 564 262" width="100%" font-family="Inter, system-ui, sans-serif"><rect width="564" height="262" fill="#fafbfc"/><line x1="442.84" y1="153.67" x2="512.82" y2="107.40" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="521.16,101.88 510.06,103.23 515.57,111.57" fill="#3a4658" stroke-linejoin="round"/><line x1="444.19" y1="165.36" x2="510.44" y2="189.94" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.81,193.41 512.18,185.25 508.70,194.62" fill="#3a4658" stroke-linejoin="round"/><line x1="409.00" y1="160.84" x2="345.00" y2="160.84" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="419.00,160.84 409.00,155.84 409.00,165.84" fill="#3a4658" stroke-linejoin="round"/><line x1="139.84" y1="219.82" x2="218.13" y2="116.28" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="224.16,108.31 214.14,113.27 222.12,119.30" fill="#3a4658" stroke-linejoin="round"/><line x1="144.96" y1="229.15" x2="509.07" y2="199.78" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.04,198.98 508.67,194.80 509.48,204.77" fill="#3a4658" stroke-linejoin="round"/><line x1="112.82" y1="217.51" x2="42.84" y2="171.24" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="121.16,223.02 115.57,213.34 110.06,221.68" fill="#3a4658" stroke-linejoin="round"/><line x1="510.16" y1="101.93" x2="344.34" y2="156.76" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.66,98.79 508.59,97.18 511.73,106.68" fill="#3a4658" stroke-linejoin="round"/><line x1="509.28" y1="91.14" x2="144.84" y2="33.83" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="519.16,92.69 510.06,86.20 508.50,96.08" fill="#3a4658" stroke-linejoin="round"/><line x1="210.16" y1="105.16" x2="44.34" y2="159.98" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="219.66,102.02 208.59,100.41 211.73,109.90" fill="#3a4658" stroke-linejoin="round"/><line x1="243.00" y1="104.86" x2="312.53" y2="148.59" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="321.00,153.92 315.19,144.36 309.87,152.82" fill="#3a4658" stroke-linejoin="round"/><line x1="212.82" y1="85.25" x2="142.84" y2="38.98" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="221.16,90.76 215.57,81.08 210.06,89.42" fill="#3a4658" stroke-linejoin="round"/><line x1="45.00" y1="163.92" x2="309.00" y2="161.09" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="319.00,160.98 308.95,156.09 309.06,166.09" fill="#3a4658" stroke-linejoin="round"/><circle cx="432.00" cy="160.84" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="432.00" y="160.84" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">0</text><circle cx="132.00" cy="230.19" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="132.00" y="230.19" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">1</text><circle cx="532.00" cy="94.71" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="532.00" y="94.71" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">2</text><circle cx="232.00" cy="97.94" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="232.00" y="97.94" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">3</text><circle cx="532.00" cy="197.94" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="532.00" y="197.94" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">4</text><circle cx="32.00" cy="164.06" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="32.00" y="164.06" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">5</text><circle cx="332.00" cy="160.84" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="332.00" y="160.84" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">6</text><circle cx="132.00" cy="31.81" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="132.00" y="31.81" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">7</text></svg>'

## Edge weights

`weighted_adjacency[i, j]` is the coefficient of variable `i` in the equation for variable `j`, so
each nonzero entry is an edge `i -> j`.

In [5]:
pd.DataFrame(results["ICA-LiNGAM"].weighted_adjacency).round(2)

      0     1     2     3     4    5     6    7
0  0.00  0.00 -0.72  0.00  0.51  0.0  0.00  0.0
1  0.00  0.00  0.00  0.94 -0.71  0.0  0.00  0.0
2  0.00  0.00  0.00  0.00  0.00  0.0  0.00  0.0
3  0.00  0.00  0.00  0.00  0.00  0.0  0.76  0.0
4  0.00  0.00  0.00  0.00  0.00  0.0  0.00  0.0
5  0.00 -0.72  0.00  0.38  0.00  0.0  0.66  0.0
6  0.79  0.00  0.47  0.00  0.00  0.0  0.00  0.0
7  0.00  0.00 -0.77  0.38  0.00  0.0  0.00  0.0

## Check accuracy over ten datasets

SHD counts errors against the true DAG; lower is better. The empty graph's SHD is the number of
true edges. The table covers ten seeds and their median.

In [6]:
methods = {
    "DirectLiNGAM": lambda X: andrey.direct_lingam(X),
    "ICA-LiNGAM": lambda X: andrey.ica_lingam(X, random_state=0),
}
rows = {}
for s in range(10):
    draw = benchmarks.scm("lingam_sf", d=8).sample(n=2000, seed=s, scale="standardize")
    d = draw.observed_graph.n_nodes
    empty = andrey.GraphStructure.from_numpy(np.zeros((d, d), dtype=np.uint8), kind="dag")
    rows[s] = {"Empty graph": metrics.score(empty, draw.observed_graph)["shd"]}
    for name, fit in methods.items():
        rows[s][name] = metrics.score(fit(draw.data), draw.observed_graph)["shd"]
shd = pd.DataFrame(rows)
shd.columns.name = "seed"
shd["median"] = shd.median(axis=1)
shd

seed           0   1   2   3   4   5   6   7   8   9  median
Empty graph   12  12  12  12  12  12  12  12  12  12    12.0
DirectLiNGAM   0   0   0   0   0   0   0   0   0   0     0.0
ICA-LiNGAM     0   0   0   0   6   0   0   0   0   1     0.0

## When to use them

Both methods rely on non-Gaussian noise. With Gaussian noise the order is not identified; PC, GES,
BOSS, or GRaSP return the CPDAG that the data do support. ICA-LiNGAM needs many samples: at
`n = 10d`, the size the [release cards](https://andrey.abel.ai/docs/benchmarks.html) use, it scores
worse than the empty graph, and this notebook uses `n = 250d`. Change `seed`, `d`, or `n` and rerun
to see how each method responds.

## Several datasets: MultiGroupDirectLiNGAM

`multi_group_direct_lingam` takes datasets over the same variables that share one causal order
and returns one result per dataset, each with its own weights. Here two groups follow the chain
`x0 -> x1 -> x2`, with different weights on `x0 -> x1`, their columns in one order drawn from the
seed.

In [7]:
CHAIN = [("x0", "x1"), ("x1", "x2")]  # the true edges, cause first


def sample_groups(seed: int, n: int = 1000, shuffle: bool = True) -> list[pd.DataFrame]:
    """Draw n rows of the chain per weight on x0 -> x1, all in one column order from the seed."""
    rng = np.random.default_rng(seed)
    groups = []
    for weight in (0.8, -1.2):
        x0 = rng.uniform(-1, 1, n)
        x1 = weight * x0 + rng.uniform(-1, 1, n)
        x2 = 0.6 * x1 + rng.uniform(-1, 1, n)
        groups.append(pd.DataFrame({"x0": x0, "x1": x1, "x2": x2}))
    columns = rng.permutation(groups[0].columns) if shuffle else groups[0].columns
    return [frame[columns] for frame in groups]


groups = sample_groups(seed=3)
for g, out in enumerate(andrey.multi_group_direct_lingam(groups)):
    weights = pd.DataFrame(
        out.weighted_adjacency, index=groups[g].columns, columns=groups[g].columns
    )
    print(f"group {g}: {out.structure.oriented_edges()}, weight {weights.loc['x0', 'x1']:.2f}")

group 0: [('x0', 'x1', 'directed'), ('x1', 'x2', 'directed')], weight 0.74
group 1: [('x0', 'x1', 'directed'), ('x1', 'x2', 'directed')], weight -1.17

## Latent variables: GIN

`gin` groups observed indicators under the latent variables that cause them and orders the
latents. Here `a1` to `a3` measure one latent and `b1` to `b3` another, which the first causes. The
indicators come in an order drawn from the seed.

In [8]:
INDICATORS = [("l1", "l2")]  # the latents l1 -> l2 have no column
INDICATORS += [("l1", f"a{i}") for i in (1, 2, 3)] + [("l2", f"b{i}") for i in (1, 2, 3)]


def sample_indicators(seed: int, n: int = 1000, shuffle: bool = True) -> pd.DataFrame:
    """Draw n rows of the six indicators of l1 -> l2, in an order drawn from the seed."""
    rng = np.random.default_rng(seed)
    l1 = rng.uniform(-1, 1, n)
    l2 = 0.9 * l1 + rng.uniform(-1, 1, n)
    loadings = {"a1": (l1, 1.0), "a2": (l1, 0.8), "a3": (l1, -1.2)}
    loadings |= {"b1": (l2, 1.0), "b2": (l2, 1.1), "b3": (l2, -0.7)}
    frame = pd.DataFrame(
        {name: w * latent + 0.3 * rng.uniform(-1, 1, n) for name, (latent, w) in loadings.items()}
    )
    return frame[rng.permutation(frame.columns)] if shuffle else frame


gin_out = andrey.gin(sample_indicators(seed=5))
print(gin_out.structure.oriented_edges())
display(andrey.viz.draw(gin_out.structure))

[('L1', 'a1', 'directed'), ('L1', 'a2', 'directed'), ('L1', 'a3', 'directed'), ('L2', 'b1', 'directed'), ('L2', 'b2', 'directed'), ('L2', 'b3', 'directed'), ('L1', 'L2', 'directed')]

'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 360 348" width="100%" font-family="Inter, system-ui, sans-serif"><rect width="360" height="348" fill="#fafbfc"/><line x1="164.25" y1="48.83" x2="88.90" y2="129.04" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="171.10,41.54 160.61,45.40 167.90,52.25" fill="#3a4658" stroke-linejoin="round"/><line x1="158.32" y1="110.72" x2="92.25" y2="134.17" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="167.75,107.38 156.65,106.01 160.00,115.44" fill="#3a4658" stroke-linejoin="round"/><line x1="158.32" y1="166.31" x2="92.25" y2="142.86" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="167.75,169.65 160.00,161.60 156.65,171.02" fill="#3a4658" stroke-linejoin="round"/><line x1="261.24" y1="187.31" x2="190.60" y2="237.44" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="269.40,181.52 258.35,183.23 264.14,191.39" fill="#3a4658" stroke-linejoin="round"/><line x1="257.00" y1="244.97" x2="193.00" y2="244.97" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="267.00,244.97 257.00,239.97 257.00,249.97" fill="#3a4658" stroke-linejoin="round"/><line x1="261.24" y1="302.62" x2="190.60" y2="252.49" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="269.40,308.41 264.14,298.55 258.35,306.70" fill="#3a4658" stroke-linejoin="round"/><line x1="88.90" y1="147.99" x2="164.25" y2="228.20" stroke="#3a4658" stroke-width="2.0" stroke-linecap="round"/><polygon points="171.10,235.49 167.90,224.78 160.61,231.63" fill="#3a4658" stroke-linejoin="round"/><circle cx="180.00" cy="32.06" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="180.00" y="32.06" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">a1</text><circle cx="180.00" cy="103.03" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="180.00" y="103.03" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">a2</text><circle cx="180.00" cy="174.00" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="180.00" y="174.00" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">a3</text><circle cx="280.00" cy="174.00" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="280.00" y="174.00" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">b1</text><circle cx="280.00" cy="244.97" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="280.00" y="244.97" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">b2</text><circle cx="280.00" cy="315.94" r="13.00" fill="#ffffff" stroke="#182233" stroke-width="1.8"/><text x="280.00" y="315.94" text-anchor="middle" font-size="11" font-weight="600" fill="#182233" dominant-baseline="central">b3</text><circle cx="80.00" cy="138.52" r="13.00" fill="#fafbfc" stroke="#5c6675" stroke-width="1.8" stroke-dasharray="3 3"/><text x="80.00" y="138.52" text-anchor="middle" font-size="11" font-weight="600" fill="#5c6675" dominant-baseline="central">L1</text><circle cx="180.00" cy="244.97" r="13.00" fill="#fafbfc" stroke="#5c6675" stroke-width="1.8" stroke-dasharray="3 3"/><text x="180.00" y="244.97" text-anchor="middle" font-size="11" font-weight="600" fill="#5c6675" dominant-baseline="central">L2</text></svg>'